1:
	gcc -g -Wall -Wextra implementation1.c -o implementation1

vim:
	nvim implementation1.c

run:
	./implementation1

memcheck:
	valgrind ./implementation1 --leak-check=full

clean:
	rm implementation1
